FROM golang:1.12.7 as builder

ENV GO111MODULE=on
ENV PORT=9000
ENV CGO_ENABLED=0

WORKDIR /app/server
COPY go.mod .
COPY go.sum .

RUN go mod download
COPY . .

RUN go build

# The final stage
FROM scratch
COPY --from=builder /app/server/server /myapp

CMD ["./myapp"]
